application: toomorechiang
version: 1-8
runtime: python
api_version: 1

handlers:
- url: .*
  script: WSGI.py
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
